# Generated by Django 3.1.3 on 2021-10-02 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20211001_1416'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myprofile', '0002_auto_20211001_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('is_rated', models.BooleanField(default=False)),
                ('rated_date', models.DateTimeField(auto_now_add=True)),
                ('order_items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
