# Generated by Django 3.1.3 on 2021-10-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pan_number',
            field=models.BigIntegerField(null=True, unique=True, verbose_name='Merchant Pan Number'),
        ),
    ]
