# Generated by Django 3.1.3 on 2021-06-23 05:53

from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedSliderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('featured_product_name', models.CharField(max_length=180)),
                ('featured_product_description', models.CharField(max_length=200)),
                ('featured_product_active', models.BooleanField(default=True)),
                ('featured_product_image', models.ImageField(upload_to=main_app.models.FeaturedSliderProduct.image_rename, verbose_name='Featured Product Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Level1ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('category_level1', models.CharField(help_text='Level1 category like electronics, health and beauty, sports and entertainment', max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Level2ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('category_level2', models.CharField(help_text='s Level2 like mobiles, laptop, soap etc.', max_length=150, unique=True)),
                ('category_name_level1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.level1productcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('product_discount_name', models.CharField(max_length=180)),
                ('product_discount_active', models.BooleanField(default=False)),
                ('product_discount_description', models.CharField(max_length=250)),
                ('product_discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('product_inventory_name', models.CharField(max_length=180)),
                ('product_inventory_quantity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_category_description', models.CharField(blank=True, max_length=250, null=True)),
                ('category_name_level2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.level2productcategory')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=500)),
                ('product_description', models.CharField(max_length=1000)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('product_availability', models.BooleanField(default=True)),
                ('product_image_src', models.ImageField(upload_to=main_app.models.Product.image_rename, verbose_name='Product Image')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.productcategory')),
                ('product_discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.productdiscount')),
                ('product_quantity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.productinventory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
