# Generated by Django 3.1.3 on 2021-10-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='level1productcategory',
            options={'verbose_name_plural': 'First Level Categories'},
        ),
        migrations.AlterModelOptions(
            name='level2productcategory',
            options={'verbose_name_plural': 'Second Level Categories'},
        ),
    ]
