# Generated by Django 3.1.3 on 2021-09-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_product_merchant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='merchant',
            new_name='user',
        ),
    ]
