# Generated by Django 3.1.3 on 2021-09-24 07:39

from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210923_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAlternativeImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_images', models.ImageField(upload_to=main_app.models.ProductAlternativeImages.image_rename, verbose_name='Product Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product')),
            ],
        ),
    ]
