# Generated by Django 3.1.3 on 2021-09-22 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210922_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='discount', to='main_app.productdiscount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='quantity', to='main_app.productinventory'),
        ),
    ]
