# Generated by Django 3.1.3 on 2021-10-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20211001_1415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level1productcategory',
            options={'verbose_name_plural': 'Level 1 Categories'},
        ),
    ]
