# Generated by Django 3.1.3 on 2021-09-14 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_orderitem_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='flag',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.order'),
        ),
    ]
