# Generated by Django 3.1.3 on 2021-09-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210914_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': (['update_date'],)},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
