# Generated by Django 3.1.3 on 2021-09-29 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main_app.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0007_auto_20210928_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP')),
                ('messages', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='productalternativeimages',
            old_name='alternative_images',
            new_name='alternative_image1',
        ),
        migrations.AddField(
            model_name='product',
            name='product_short_description',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productalternativeimages',
            name='alternative_image2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=main_app.models.ProductAlternativeImages.image_rename, verbose_name='Product Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productalternativeimages',
            name='alternative_image3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=main_app.models.ProductAlternativeImages.image_rename, verbose_name='Product Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='product_inventory_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
