# Generated by Django 3.1.3 on 2021-09-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210914_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
