# Generated by Django 3.1.3 on 2021-09-14 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210914_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': (['modified_date'],)},
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='update_date',
            new_name='modified_date',
        ),
    ]
