# Generated by Django 3.1.3 on 2021-09-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210929_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_short_description',
            field=models.TextField(),
        ),
    ]
