# Generated by Django 3.1.3 on 2021-09-30 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210929_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='messaged_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
