# Generated by Django 3.1.3 on 2021-09-30 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_contactus_messaged_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productalternativeimages',
            old_name='alternative_image1',
            new_name='alternative_image',
        ),
        migrations.RemoveField(
            model_name='productalternativeimages',
            name='alternative_image2',
        ),
        migrations.RemoveField(
            model_name='productalternativeimages',
            name='alternative_image3',
        ),
    ]
