# Generated by Django 3.1.3 on 2021-09-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210930_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productalternativeimages',
            options={'verbose_name_plural': 'Alternative Image'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
