# Generated by Django 3.1.3 on 2021-09-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210914_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-added_date']},
        ),
    ]
