# Generated by Django 3.1.3 on 2021-09-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20210915_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
    ]
