# Generated by Django 3.1.3 on 2021-09-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_shippingaddress_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='same_billing_address',
        ),
    ]
