# Generated by Django 3.1.3 on 2021-09-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_remove_shippingaddress_same_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.BigIntegerField(blank=True, max_length=10, null=True),
        ),
    ]
