# Generated by Django 3.1.3 on 2021-09-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_orderitem_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='level2productcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='productdiscount',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
    ]
