# Generated by Django 3.1.3 on 2021-09-18 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_auto_20210916_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.productinventory'),
        ),
    ]
