# Generated by Django 3.1.3 on 2021-09-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_auto_20210918_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
