# Generated by Django 3.1.3 on 2021-09-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_auto_20210918_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='brand_name',
            field=models.CharField(max_length=100),
        ),
    ]
