# Generated by Django 3.1.3 on 2021-09-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_auto_20210919_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='product_discount_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='product_discount_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='product_discount_name',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='product_discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='product_inventory_name',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
